import { Tile } from './types';

export const BOARD: Tile[] = [
  {
    id: 'go',
    index: 0,
    name: 'GO',
    type: 'go',
    description: 'Collect $200 when you pass.',
  },
  {
    id: 'mediterranean',
    index: 1,
    name: 'Mediterranean Avenue',
    type: 'street',
    group: 'brown',
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    mortgageValue: 30,
    houseCost: 50,
  },
  {
    id: 'chest1',
    index: 2,
    name: 'Community Chest',
    type: 'community_chest',
    description: 'Draw a Community Chest card.',
  },
  {
    id: 'baltic',
    index: 3,
    name: 'Baltic Avenue',
    type: 'street',
    group: 'brown',
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    mortgageValue: 30,
    houseCost: 50,
  },
  {
    id: 'tax1',
    index: 4,
    name: 'Income Tax',
    type: 'tax',
    price: 200,
    description: 'Pay the tax amount shown.',
  },
  {
    id: 'reading_rr',
    index: 5,
    name: 'Reading Railroad',
    type: 'railroad',
    group: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
  },
  {
    id: 'oriental',
    index: 6,
    name: 'Oriental Avenue',
    type: 'street',
    group: 'light_blue',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    mortgageValue: 50,
    houseCost: 50,
  },
  {
    id: 'chance1',
    index: 7,
    name: 'Chance',
    type: 'chance',
    description: 'Draw a Chance card.',
  },
  {
    id: 'vermont',
    index: 8,
    name: 'Vermont Avenue',
    type: 'street',
    group: 'light_blue',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    mortgageValue: 50,
    houseCost: 50,
  },
  {
    id: 'connecticut',
    index: 9,
    name: 'Connecticut Avenue',
    type: 'street',
    group: 'light_blue',
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    mortgageValue: 60,
    houseCost: 50,
  },
  {
    id: 'jail',
    index: 10,
    name: 'Jail / Just Visiting',
    type: 'jail',
    description: 'If you land here, you are just visiting. If sent here, you are in Jail.',
  },
  {
    id: 'st_charles',
    index: 11,
    name: 'St. Charles Place',
    type: 'street',
    group: 'pink',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    mortgageValue: 70,
    houseCost: 100,
  },
  {
    id: 'electric',
    index: 12,
    name: 'Electric Company',
    type: 'utility',
    group: 'utility',
    price: 150,
    mortgageValue: 75,
  },
  {
    id: 'states',
    index: 13,
    name: 'States Avenue',
    type: 'street',
    group: 'pink',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    mortgageValue: 70,
    houseCost: 100,
  },
  {
    id: 'virginia',
    index: 14,
    name: 'Virginia Avenue',
    type: 'street',
    group: 'pink',
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    mortgageValue: 80,
    houseCost: 100,
  },
  {
    id: 'penn_rr',
    index: 15,
    name: 'Pennsylvania Railroad',
    type: 'railroad',
    group: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
  },
  {
    id: 'st_james',
    index: 16,
    name: 'St. James Place',
    type: 'street',
    group: 'orange',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    mortgageValue: 90,
    houseCost: 100,
  },
  {
    id: 'chest2',
    index: 17,
    name: 'Community Chest',
    type: 'community_chest',
    description: 'Draw a Community Chest card.',
  },
  {
    id: 'tennessee',
    index: 18,
    name: 'Tennessee Avenue',
    type: 'street',
    group: 'orange',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    mortgageValue: 90,
    houseCost: 100,
  },
  {
    id: 'new_york',
    index: 19,
    name: 'New York Avenue',
    type: 'street',
    group: 'orange',
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    mortgageValue: 100,
    houseCost: 100,
  },
  {
    id: 'parking',
    index: 20,
    name: 'Free Parking',
    type: 'parking',
    description: 'No action.',
  },
  {
    id: 'kentucky',
    index: 21,
    name: 'Kentucky Avenue',
    type: 'street',
    group: 'red',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    mortgageValue: 110,
    houseCost: 150,
  },
  {
    id: 'chance2',
    index: 22,
    name: 'Chance',
    type: 'chance',
    description: 'Draw a Chance card.',
  },
  {
    id: 'indiana',
    index: 23,
    name: 'Indiana Avenue',
    type: 'street',
    group: 'red',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    mortgageValue: 110,
    houseCost: 150,
  },
  {
    id: 'illinois',
    index: 24,
    name: 'Illinois Avenue',
    type: 'street',
    group: 'red',
    price: 240,
    rent: [20, 100, 300, 750, 925, 1100],
    mortgageValue: 120,
    houseCost: 150,
  },
  {
    id: 'bo_rr',
    index: 25,
    name: 'B. & O. Railroad',
    type: 'railroad',
    group: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
  },
  {
    id: 'atlantic',
    index: 26,
    name: 'Atlantic Avenue',
    type: 'street',
    group: 'yellow',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    mortgageValue: 130,
    houseCost: 150,
  },
  {
    id: 'ventnor',
    index: 27,
    name: 'Ventnor Avenue',
    type: 'street',
    group: 'yellow',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    mortgageValue: 130,
    houseCost: 150,
  },
  {
    id: 'water',
    index: 28,
    name: 'Water Works',
    type: 'utility',
    group: 'utility',
    price: 150,
    mortgageValue: 75,
  },
  {
    id: 'marvin',
    index: 29,
    name: 'Marvin Gardens',
    type: 'street',
    group: 'yellow',
    price: 280,
    rent: [24, 120, 360, 850, 1025, 1200],
    mortgageValue: 140,
    houseCost: 150,
  },
  {
    id: 'go_to_jail',
    index: 30,
    name: 'Go To Jail',
    type: 'go_to_jail',
    description: 'Go directly to Jail. Do not pass GO, do not collect $200.',
  },
  {
    id: 'pacific',
    index: 31,
    name: 'Pacific Avenue',
    type: 'street',
    group: 'green',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    mortgageValue: 150,
    houseCost: 200,
  },
  {
    id: 'north_carolina',
    index: 32,
    name: 'North Carolina Avenue',
    type: 'street',
    group: 'green',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    mortgageValue: 150,
    houseCost: 200,
  },
  {
    id: 'chest3',
    index: 33,
    name: 'Community Chest',
    type: 'community_chest',
    description: 'Draw a Community Chest card.',
  },
  {
    id: 'pennsylvania',
    index: 34,
    name: 'Pennsylvania Avenue',
    type: 'street',
    group: 'green',
    price: 320,
    rent: [28, 150, 450, 1000, 1200, 1400],
    mortgageValue: 160,
    houseCost: 200,
  },
  {
    id: 'short_rr',
    index: 35,
    name: 'Short Line',
    type: 'railroad',
    group: 'railroad',
    price: 200,
    rent: [25, 50, 100, 200],
    mortgageValue: 100,
  },
  {
    id: 'chance3',
    index: 36,
    name: 'Chance',
    type: 'chance',
    description: 'Draw a Chance card.',
  },
  {
    id: 'park',
    index: 37,
    name: 'Park Place',
    type: 'street',
    group: 'dark_blue',
    price: 350,
    rent: [35, 175, 500, 1100, 1300, 1500],
    mortgageValue: 175,
    houseCost: 200,
  },
  {
    id: 'tax2',
    index: 38,
    name: 'Luxury Tax',
    type: 'tax',
    price: 100,
    description: 'Pay the tax amount shown.',
  },
  {
    id: 'boardwalk',
    index: 39,
    name: 'Boardwalk',
    type: 'street',
    group: 'dark_blue',
    price: 400,
    rent: [50, 200, 600, 1400, 1700, 2000],
    mortgageValue: 200,
    houseCost: 200,
  },
];

export const isTileBuyable = (tile: Tile): boolean => {
  return !['tax', 'go', 'jail', 'parking', 'chance', 'community_chest', 'go_to_jail'].includes(
    tile.type
  );
};
